name: CI


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  build:

    runs-on: ubuntu-latest 

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: build image 
        run: | 
              docker build -t ${{secrets.REG_USER}}/portfolio:${{github.run_number}} .
              docker build  -t ${{secrets.REG_USER}}/portfolio  .

      - name: Image scan 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{secrets.REG_USER}}/portfolio:${{github.run_number}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: push image 
        run: | 
            docker login -u ${{secrets.REG_USER}} -p ${{secrets.REG_PASS}}
        
            docker push ${{secrets.REG_USER}}/portfolio:${{github.run_number}}  
            docker push ${{secrets.REG_USER}}/portfolio    
            
  
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          #port: ${{ secrets.PORT }}
          script: | 
            echo "Logging into ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            
            echo "Stopping old container..."
            docker rm -f resume || echo "No existing container"

            echo "Running new container..."
            docker run -d --name resume -p 8080:5001 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

          